configuration:
    env:
     - name: AUTH_SERVER_ENDPOINT
       value: https://gwad0-test.syssede.systest.sanpaoloimi.com/auth/oauth
     - name: CALL_MOCK
       value: N
    ctg:
     - name: COND0
       acronimo: COND0
       servizio: COND0-CTGBS
       env: TEST
       user: GACONNEC