/*
 * GESTIONE
 * test
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.intesasanpaolo.bear.cond0.cjdispositiva.connector.rest.pcgestixme;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Setter;

import java.util.Objects;

import static com.intesasanpaolo.bear.cond0.cjdispositiva.utils.ApplicationConstants.COBOL_EMPTY;
/**
 * InputDatiInputAreaRapportoPrincipale
 */
@Setter
public class InputDatiInputAreaRapportoPrincipale {

    private String fiLRapp = COBOL_EMPTY;
    private String caTRapp = COBOL_EMPTY;
    private String numProgRapp = COBOL_EMPTY;

    @JsonProperty("FILRapp")
    public String getFiLRapp() {
        return fiLRapp;
    }

    @JsonProperty("CATRapp")
    public String getCaTRapp() {
        return caTRapp;
    }

    @JsonProperty("NumProgRapp")
    public String getNumProgRapp() {
        return numProgRapp;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InputDatiInputAreaRapportoPrincipale inputDatiInputAreaRapportoPrincipale = (InputDatiInputAreaRapportoPrincipale) o;
        return Objects.equals(fiLRapp, inputDatiInputAreaRapportoPrincipale.fiLRapp) &&
                Objects.equals(caTRapp, inputDatiInputAreaRapportoPrincipale.caTRapp) &&
                Objects.equals(numProgRapp, inputDatiInputAreaRapportoPrincipale.numProgRapp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(fiLRapp, caTRapp, numProgRapp);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InputDatiInputAreaRapportoPrincipale {\n");

        sb.append("    fiLRapp: ").append(toIndentedString(fiLRapp)).append("\n");
        sb.append("    caTRapp: ").append(toIndentedString(caTRapp)).append("\n");
        sb.append("    numProgRapp: ").append(toIndentedString(numProgRapp)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
