spring:
  application:
    name: "@project.artifactId@"
    version: "@project.version@ (@env.GIT_COMMIT@)"
  jackson:
    time-zone: Europe/Rome
  profiles:
    active: ${ISP_AMBIENTE}
    

logging:
  level:
    root: INFO
    com.intesasanpaolo.bear: INFO
    com.intesasanpaolo.bear.config: INFO
    com.intesasanpaolo.bear.connector.bearcore: INFO
    com.intesasanpaolo.bear.cond0.cjindicatoricosto: DEBUG
    org.keycloak: INFO

error-manager:
  enabled: true
  
tracing:
  enabled: true
  
controllers:
    tracing:
        enabled: true
        bodyMaxLength: 10000

connectors:
  jdbcConfigurations:
     items:
         GenericJdbcConnector:
           uri: ${DATASOURCE_CONDDATA_URL}
           driver-class-name: oracle.jdbc.OracleDriver
           username: ${DATASOURCE_CONDDATA_USERNAME}
           password: ${DATASOURCE_CONDDATA_PASSWORD}
           connectionPoolSize: ${DATASOURCE_CONDDATA_MAX_POOL_SIZE}
           timeout: ${DATASOURCE_CONDDATA_CONNECTION_TIMEOUT}




hostbridge:
  # added to mock CTG call
  mocked: false
#  mocked: true
  connectorFileProps:
    ServerConfig.section: ${ISP_AMBIENTE}
    ServerConfig.path: ""
  y1j2cConfigFileProps:
    #Y1.j2cConfigProperties: ""
    Y1.StgY: StgA
    Y1.ApiStage: "01"
    Y1.Acronimo: COND0
    Y1.ExecuteTimeout: 120000
    Y1.displaycommArea: ${CTG_DISPLAY_COMMON_AREA}
    Y1.CTGConnectionURL: ${CTG_COND0_HOSTNAME}
    Y1.CTGPortNumberSSL: ${CTG_COND0_PORT}
    Y1.CTGPortNumberTcpIP: ${CTG_COND0_PORT}
    Y1.CTGCUserName: ${CTG_COND0_USERNAME}
    Y1.CTGPassword: ${CTG_COND0_PASSWORD}
    Y1.CTGSSL: ${CTG_COND0_SSL}
 


#### Security configuration: Everything allowed for test
keycloak:
  enabled: false
  auth-server-url: ${AUTH_SERVER_ENDPOINT}
  resource: bear-app
  realm: bear
  public-client: true
  ssl-required: external
  confidential-port: 0
  use-resource-role-mappings: true
  securityConstraints:
    -
      authRoles:
        - users

      securityCollections:
        -
          name: users reserved stuff
          patterns:
            - /preferences
