spring:
  profile: development
  application:
    name: "@project.artifactId@"
    version: "@project.version@ (@env.GIT_COMMIT@)"
  jackson:
    time-zone: Europe/Rome
  profiles:
    active: ${ISP_AMBIENTE}
    
logging:
  level:
    root: INFO
    com.intesasanpaolo.bear: INFO
    com.intesasanpaolo.bear.config: INFO
    com.intesasanpaolo.bear.connector.bearcore: INFO
    com.intesasanpaolo.bear.cond0.cjindicatoricosto: DEBUG
    org.keycloak: INFO

error-manager:
  enabled: true
  
tracing:
  enabled: true
 #mocked: true

controllers:
  tracing:
    enabled: true

connectors:
  db2MultiDsConfigurations:
    items:
      MultiDataSourceDb2Connector:
        connectionTimeout: ${DATASOURCE_SPIMI_DB2_CONNECTIONTIMEOUT:8000}
        connectionPoolSize: ${DATASOURCE_SPIMI_DB2_CONNECTIONPOOLSIZE:30}
        mocked: false
        sources:
          - abi: ${ABI_SPIMI:01025}
            uri: ${DATASOURCE_SPIMI_DB2_URI:sdda.mframe.sanpaoloimi.com}
            port: ${DATASOURCE_SPIMI_DB2_PORT:5300}
            dbName: ${DATASOURCE_SPIMI_DB2_DBNAME:SDDAM00S}
            readUsername: ${DATASOURCE_SPIMI_DB2_USERNAME:U0H7129}
            readPassword: ${DATASOURCE_SPIMI_DB2_PASSWORD:Alma1020}
            writeUsername: ${DATASOURCE_SPIMI_DB2_USERNAME:U0H7129}
            writePassword: ${DATASOURCE_SPIMI_DB2_PASSWORD:Alma1020}      
            #puntamenti per system
            #uri: ${DATASOURCE_SPIMI_DB2_URI:sdda.mframe.sanpaoloimi.com}
            #port: ${DATASOURCE_SPIMI_DB2_PORT:5300}
            #dbName: ${DATASOURCE_SPIMI_DB2_DBNAME:SDDAM00S}
            #readUsername: ${DATASOURCE_SPIMI_DB2_USERNAME:U0G6425}
            #readPassword: ${DATASOURCE_SPIMI_DB2_PASSWORD:Alma0720}
            #writeUsername: ${DATASOURCE_SPIMI_DB2_USERNAME:U0G6425}
            #writePassword: ${DATASOURCE_SPIMI_DB2_PASSWORD:Alma0720}    
                    
          
          - abi: ${ABI_BKFID:03296}
            uri: ${DATASOURCE_BKFID_DB2_URI:mdda.mframe.sanpaoloimi.com}
            port: ${DATASOURCE_BKFID_DB2_PORT:18588}
            dbName: ${DATASOURCE_BKFID_DB2_DBNAME:MDDAM00S}
            readUsername: ${DATASOURCE_BKFID_DB2_USERNAME:U0G6425}
            readPassword: ${DATASOURCE_BKFID_DB2_PASSWORD:Alma0720}
            writeUsername: ${DATASOURCE_BKFID_DB2_USERNAME:U0G6425}
            writePassword: ${DATASOURCE_BKFID_DB2_PASSWORD:Alma0720}    
          
          - abi: ${ABI_ISPBK:03239}
            uri: ${DATASOURCE_ISPBK_DB2_URI:jdda.mframe.sanpaoloimi.com}
            port: ${DATASOURCE_ISPBK_DB2_PORT:18607}
            dbName: ${DATASOURCE_ISPBK_DB2_DBNAME:JDDAM00S}
            readUsername: ${DATASOURCE_ISPBK_DB2_USERNAME:U0G6425}
            readPassword: ${DATASOURCE_ISPBK_DB2_PASSWORD:Alma0720}
            writeUsername: ${DATASOURCE_ISPBK_DB2_USERNAME:U0G6425}
            writePassword: ${DATASOURCE_ISPBK_DB2_PASSWORD:Alma0720}    
                    
          - abi: ${ABI_BKIMI:03249}
            uri: ${DATASOURCE_BKIMI_DB2_URI:idda.mframe.sanpaoloimi.com}
            port: ${DATASOURCE_BKIMI_DB2_PORT:5449}
            dbName: ${DATASOURCE_BKIMI_DB2_DBNAME:IDDAM00S}
            readUsername: ${DATASOURCE_BKIMI_DB2_USERNAME:U0G6425}
            readPassword: ${DATASOURCE_BKIMI_DB2_PASSWORD:Alma0720}
            writeUsername: ${DATASOURCE_BKIMI_DB2_USERNAME:U0G6425}
            writePassword: ${DATASOURCE_BKIMI_DB2_PASSWORD:Alma0720}
            
  jdbcConfigurations:
     items:
         GenericJdbcConnector:
           uri: ${DATASOURCE_CONDDATA_URL:jdbc:oracle:thin:@sdlvms1039.sede.corp.sanpaoloimi.com:2169/TCOND0}
           driver-class-name: oracle.jdbc.OracleDriver
           username: ${DATASOURCE_CONDDATA_USERNAME:COND_APP}
           password: ${DATASOURCE_CONDDATA_PASSWORD:COND_APP}
           connectionPoolSize: ${DATASOURCE_CONDDATA_MAX_POOL_SIZE:30}
           timeout: ${DATASOURCE_CONDDATA_CONNECTION_TIMEOUT:5000}
           
hostbridge:
  # added to mock CTG call
  mocked: false
#  mocked: true
  connectorFileProps:
    ServerConfig.section: ${ISP_AMBIENTE}
    ServerConfig.path: ""
  y1j2cConfigFileProps:
    #Y1.j2cConfigProperties: ""
    Y1.StgY: StgA
    Y1.ApiStage: "01"
    Y1.Acronimo: COND0
    Y1.ExecuteTimeout: 120000
    Y1.displaycommArea: ${CTG_DISPLAY_COMMON_AREA:true}
    Y1.CTGConnectionURL: ${CTG_COND0_HOSTNAME:ctxgga0.mframe.sanpaoloimi.com}
    Y1.CTGPortNumberSSL: ${CTG_COND0_PORT:18617}
    Y1.CTGPortNumberTcpIP: ${CTG_COND0_PORT:18617}
    Y1.CTGCUserName: ${CTG_COND0_USERNAME:GACONNEC}
    Y1.CTGPassword: ${CTG_COND0_PASSWORD:secret}
    Y1.CTGSSL: ${CTG_COND0_SSL:false}
  # added to mock CTG call
  #servicesFileProps:
  #  com.dsi.business.SSA_Z3.integration.jdo.P_Z3YCS00.fileMode: true
  #  com.dsi.business.SSA_Z3.integration.jdo.P_Z3YCS00.C_Z3YCS00.file: classpath:mocks/CTG/Z3YC_out.txt
  #  com.dsi.business.SSA_AF.integration.jdo.P_AFDYS04.C_AFDYS04.file: classpath:mocks/CTG/AFDY_out.txt
  #  com.dsi.business.SSA_AF.integration.jdo.P_AFRJS03.C_AFRJS03.file: classpath:mocks/CTG/AFRJ_out.txt
#  transportsFileProps:
#    mqtestGroup.transport: MQ
#    mqtestGroup.trials: 2
#    mqtestGroup.resumetime: 1
  #tracerFileProps:
  #  com.dsi.business.SSA_FL.integration.jdo.P_FL03S00.C_FL03S00.traceClass.Name_0: connector.log.DefaultTraceClass
  #  com.dsi.business.SSA_T1.integration.jdo.P_T1SFS00.C_T1SFS00.traceClass.Name_0: connector.log.DefaultTraceClass