spring:
  profile: development
  application:
    name: "@project.artifactId@"
    version: "@project.version@ (@env.GIT_COMMIT@)"
  profiles:
    active: ${ISP_AMBIENTE}
CALL_MOCK: ${CALL_MOCK}
error-manager:
  enabled: true

hostbridge:
  # added to mock CTG call
  mocked: false
#  mocked: true
  connectorFileProps:
    ServerConfig.section: ${ISP_AMBIENTE}
    ServerConfig.path: ""
  y1j2cConfigFileProps:
    Y1.StgY: StgA
    Y1.ApiStage: "01"
    Y1.Acronimo: COND0
    Y1.ExecuteTimeout: 120000
    Y1.displaycommArea: ${CTG_DISPLAY_COMMON_AREA}
    Y1.CTGConnectionURL: ${CTG_COND0_HOSTNAME}
    Y1.CTGPortNumberSSL: ${CTG_COND0_PORT}
    Y1.CTGPortNumberTcpIP: ${CTG_COND0_PORT}
    Y1.CTGCUserName: ${CTG_COND0_USERNAME}
    Y1.CTGPassword: ${CTG_COND0_PASSWORD}
    Y1.CTGSSL: ${CTG_COND0_SSL}

connectors:
  #restConfigurations:
  #  -
  #    name: BitCoinRestConnector
  #    url: https://api.blockchain.info/stats

#### Security configuration: Everything allowed for test
keycloak:
  enabled: false
  auth-server-url: http://192.168.99.100:31233/auth
  resource: bear-app
  realm: bear
  public-client: true
  ssl-required: external
  confidential-port: 0
  use-resource-role-mappings: true
  securityConstraints:
    -
      authRoles:
        - users

      securityCollections:
        -
          name: users reserved stuff
          patterns:
            - /preferences
