spring:
  profile: development
  application:
    name: "@project.artifactId@"
    version: "@project.version@ (@env.GIT_COMMIT@)"
  jackson:
    time-zone: Europe/Rome
  profiles:
    active: ${ISP_AMBIENTE}

logging:
  level:
    root: INFO
    com.intesasanpaolo.bear: INFO
    com.intesasanpaolo.bear.config: INFO
    com.intesasanpaolo.bear.connector.bearcore: INFO
    org.keycloak: INFO

error-manager:
  enabled: true

controllers:
    tracing:
        enabled: true
        bodyMaxLength: 10000
tracing:
    enabled: true

hostbridge:
  # added to mock CTG call
  mocked: false
#  mocked: true
  connectorFileProps:
    ServerConfig.section: ${ISP_AMBIENTE}
    ServerConfig.path: ""
  y1j2cConfigFileProps:
    Y1.StgY: StgA
    Y1.ApiStage: "01"
    Y1.Acronimo: COND0
    Y1.ExecuteTimeout: 120000
    Y1.displaycommArea: ""
    Y1.CTGConnectionURL: ""
    Y1.CTGPortNumberSSL: ""
    Y1.CTGPortNumberTcpIP: ""
    Y1.CTGCUserName: ""
    Y1.CTGPassword: ""
    Y1.CTGSSL: ""
    
keycloak:
  enabled: false
  auth-server-url: ${AUTH_SERVER_ENDPOINT}
  resource: bear-app
  realm: bear
  public-client: true
  ssl-required: external
  confidential-port: 0
  use-resource-role-mappings: true
  securityConstraints:
    -
      authRoles:
        - users

      securityCollections:
        -
          name: users reserved stuff
          patterns:
            - /preferences
