spring:
  profile: development
  application:
    name: "@project.artifactId@"
    version: "@project.version@ (@env.GIT_COMMIT@)"
  jackson:
    time-zone: Europe/Rome
  profiles:
    active: ${ISP_AMBIENTE}
    
logging:
  level:
    root: DEBUG
    com.intesasanpaolo.bear: DEBUG
    com.intesasanpaolo.bear.config: DEBUG
    com.intesasanpaolo.bear.connector.bearcore: DEBUG
    org.keycloak: INFO

error-manager:
  enabled: false

#connectors:
  #restConfigurations:
  #  -
  #    name: BitCoinRestConnector
  #    url: https://api.blockchain.info/stats



hostbridge:
  # added to mock CTG call
  mocked: false
#  mocked: true
  connectorFileProps:
    ServerConfig.section: ${ISP_AMBIENTE}
    ServerConfig.path: ""
  y1j2cConfigFileProps:
    #Y1.j2cConfigProperties: ""
    Y1.StgY: StgA
    Y1.ApiStage: "01"
    Y1.Acronimo: COND0
    Y1.ExecuteTimeout: 120000
    Y1.displaycommArea: ${CTG_DISPLAY_COMMON_AREA:true}
    Y1.CTGConnectionURL: ${CTG_COND0_HOSTNAME:ctxgga0.mframe.sanpaoloimi.com}
    Y1.CTGPortNumberSSL: ${CTG_COND0_PORT:18617}
    Y1.CTGPortNumberTcpIP: ${CTG_COND0_PORT:18617}
    Y1.CTGCUserName: ${CTG_COND0_USERNAME:GACONNEC}
    Y1.CTGPassword: ${CTG_COND0_PASSWORD:secret}
    Y1.CTGSSL: ${CTG_COND0_SSL:false}
  # added to mock CTG call
  #servicesFileProps:
  #  com.dsi.business.SSA_Z3.integration.jdo.P_Z3YCS00.fileMode: true
  #  com.dsi.business.SSA_Z3.integration.jdo.P_Z3YCS00.C_Z3YCS00.file: classpath:mocks/CTG/Z3YC_out.txt
  #  com.dsi.business.SSA_AF.integration.jdo.P_AFDYS04.C_AFDYS04.file: classpath:mocks/CTG/AFDY_out.txt
  #  com.dsi.business.SSA_AF.integration.jdo.P_AFRJS03.C_AFRJS03.file: classpath:mocks/CTG/AFRJ_out.txt
#  transportsFileProps:
#    mqtestGroup.transport: MQ
#    mqtestGroup.trials: 2
#    mqtestGroup.resumetime: 1
 # tracerFileProps:
  #  com.dsi.business.SSA_Z3.integration.jdo.P_Z3YCS00.C_Z3YCS00.traceClass.Name_0: connector.log.DefaultTraceClass
   # com.dsi.business.SSA_AF.integration.jdo.P_AFDYS04.C_AFDYS04.traceClass.Name_0: connector.log.DefaultTraceClass
   # com.dsi.business.SSA_AF.integration.jdo.P_AFRJS03.C_AFRJS03.traceClass.Name_0: connector.log.DefaultTraceClass

connectors:
  soapConfiguration:
   items:
     ConvenzioniHostServiceConnector:
       endpoint: ${CONVENZIONI_HOST_SERVICE_WS_URL:http://servizibe-vdmc0.syssede.systest.sanpaoloimi.com:9018/ConvenzioniHostService.svc}
       timeout: 60000
       username: username
       password: password
       authenticationType: none
       timeToLive: 7000
       contextPath: "com.intesasanpaolo.bear.cond0.cjadesioneconvenzione.connector.ws.gen.convenzionihostservice"
       soapVersion: 1.1
       soapAction: "http://tempuri.org/IConvenzioniHostService/GetCovenantPerConvenzione"
       enableMTOM: false
       mocked: false
     ConvenzioniServiceConnector:
       endpoint: ${CONVENZIONI_SERVICE_WS_URL:http://servizibe-vdmc0.syssede.systest.sanpaoloimi.com:9018/ConvenzioniService.svc}
       timeout: 60000
       username: username
       password: password
       authenticationType: none
       timeToLive: 7000
       contextPath: "com.intesasanpaolo.bear.cond0.cjadesioneconvenzione.connector.ws.gen.convenzioniservice"
       soapVersion: 1.1
       soapAction: "http://tempuri.org/IConvenzioniService/GetRequisitiAdesioneConvenzione"
       enableMTOM: false
       mocked: false

#### Security configuration: Everything allowed for test
keycloak:
  enabled: false
  auth-server-url: ${AUTH_SERVER_ENDPOINT}
  resource: bear-app
  realm: bear
  public-client: true
  ssl-required: external
  confidential-port: 0
  use-resource-role-mappings: true
  securityConstraints:
    -
      authRoles:
        - users

      securityCollections:
        -
          name: users reserved stuff
          patterns:
            - /preferences
