DATASOURCE_DB2_ACCOUNTING_ACRONYM: cond0
DATASOURCE_DB2_ACCOUNTING_SERVICE_NAME: core-price-cjadesioneconvenzione-v1
spring:
  profile: development
  application:
    name: "@project.artifactId@"
    version: "@project.version@ (@env.GIT_COMMIT@)"
  jackson:
    time-zone: Europe/Rome
  profiles:
    active: ${ISP_AMBIENTE}
    
logging:
  level:
    root: INFO
    com.intesasanpaolo.bear: INFO
    com.intesasanpaolo.bear.config: INFO
    com.intesasanpaolo.bear.connector.bearcore: INFO
    com.intesasanpaolo.bear.cond0.cjadesioneconvenzione: DEBUG
    org.keycloak: INFO

error-manager:
  enabled: true

controllers:
    tracing:
        enabled: true
        bodyMaxLength: 10000
tracing:
    enabled: true

hostbridge:
  # added to mock CTG call
  mocked: false
#  mocked: true
  connectorFileProps:
    ServerConfig.section: ${ISP_AMBIENTE}
    ServerConfig.path: ""
  y1j2cConfigFileProps:
    #Y1.j2cConfigProperties: ""
    Y1.StgY: StgA
    Y1.ApiStage: "01"
    Y1.Acronimo: COND0
    Y1.ExecuteTimeout: 120000
    Y1.displaycommArea: ${CTG_DISPLAY_COMMON_AREA:true}
    Y1.CTGConnectionURL: ${CTG_COND0_HOSTNAME:ctxgga0.mframe.sanpaoloimi.com}
    Y1.CTGPortNumberSSL: ${CTG_COND0_PORT:18617}
    Y1.CTGPortNumberTcpIP: ${CTG_COND0_PORT:18617}
    Y1.CTGCUserName: ${CTG_COND0_USERNAME:GACONNEC}
    Y1.CTGPassword: ${CTG_COND0_PASSWORD:secret}
    Y1.CTGSSL: ${CTG_COND0_SSL:false}


connectors:
  db2MultiDsConfigurations:
    items:
      MultiDataSourceDb2Connector:
        connectionTimeout: ${DATASOURCE_DB2_CONNECTIONTIMEOUT:8000}
        connectionPoolSize: ${DATASOURCE_DB2_CONNECTIONPOOLSIZE:30}
        mocked: false
        sources:
          - abi: ${ABI_SPIMI:01025}
            uri: ${DATASOURCE_SPIMI_DB2_URI:db2y.mframe.sanpaoloimi.com}
            port: ${DATASOURCE_SPIMI_DB2_PORT:5250}
            dbName: ${DATASOURCE_SPIMI_DB2_DBNAME:DB2YTOSG}
            readUsername: ${DATASOURCE_SPIMI_DB2_USERNAME:U0G6425}
            readPassword: ${DATASOURCE_SPIMI_DB2_PASSWORD:Alma0720}
            writeUsername: ${DATASOURCE_SPIMI_DB2_USERNAME:U0G6425}
            writePassword: ${DATASOURCE_SPIMI_DB2_PASSWORD:Alma0720}    
            #puntamenti per system
            #uri: ${DATASOURCE_SPIMI_DB2_URI:sdda.mframe.sanpaoloimi.com}
            #port: ${DATASOURCE_SPIMI_DB2_PORT:5300}  U0G6425 Alma0720
            #dbName: ${DATASOURCE_SPIMI_DB2_DBNAME:SDDAM00S}
            #readUsername: ${DATASOURCE_SPIMI_DB2_USERNAME:u0h7129}
            #readPassword: ${DATASOURCE_SPIMI_DB2_PASSWORD:Alma0720}
            #writeUsername: ${DATASOURCE_SPIMI_DB2_USERNAME:u0h7129}
            #writePassword: ${DATASOURCE_SPIMI_DB2_PASSWORD:Alma0720}    
          #- abi: ${ABI_BKFID:03296}
          #  uri: ${DATASOURCE_BKFID_DB2_URI:mdda.mframe.sanpaoloimi.com}
          #  port: ${DATASOURCE_BKFID_DB2_PORT:18588}
          #  dbName: ${DATASOURCE_BKFID_DB2_DBNAME:MDDAM00S}
          #  readUsername: ${DATASOURCE_BKFID_DB2_USERNAME:U0G6425}
       #     readPassword: ${DATASOURCE_BKFID_DB2_PASSWORD:Alma0720}
       #     writeUsername: ${DATASOURCE_BKFID_DB2_USERNAME:U0G6425}
       #     writePassword: ${DATASOURCE_BKFID_DB2_PASSWORD:Alma0720}    
       #   - abi: ${ABI_ISPBK:03239}
       #     uri: ${DATASOURCE_ISPBK_DB2_URI:jdda.mframe.sanpaoloimi.com}
       #     port: ${DATASOURCE_ISPBK_DB2_PORT:18607}
       #     dbName: ${DATASOURCE_ISPBK_DB2_DBNAME:JDDAM00S}
       #     readUsername: ${DATASOURCE_ISPBK_DB2_USERNAME:U0G6425}
       #     readPassword: ${DATASOURCE_ISPBK_DB2_PASSWORD:Alma0720}
       #     writeUsername: ${DATASOURCE_ISPBK_DB2_USERNAME:U0G6425}
       #     writePassword: ${DATASOURCE_ISPBK_DB2_PASSWORD:Alma0720}                      
         # - abi: ${ABI_BKIMI:03249}
          #  uri: ${DATASOURCE_BKIMI_DB2_URI:idda.mframe.sanpaoloimi.com}
          #  port: ${DATASOURCE_BKIMI_DB2_PORT:5449}
          #  dbName: ${DATASOURCE_BKIMI_DB2_DBNAME:IDDAM00S}
         #   readUsername: ${DATASOURCE_BKIMI_DB2_USERNAME:U0G6425}
          #  readPassword: ${DATASOURCE_BKIMI_DB2_PASSWORD:Alma0720}
          #  writeUsername: ${DATASOURCE_BKIMI_DB2_USERNAME:U0G6425}
          #  writePassword: ${DATASOURCE_BKIMI_DB2_PASSWORD:Alma0720}

  soapConfiguration:
   items:
     GetCovenantPerConvenzioneConnector:
       endpoint: ${CONVENZIONI_HOST_SERVICE_WS_URL:http://servizibe-vdmc0.syssede.systest.sanpaoloimi.com:9018/ConvenzioniHostService.svc}
       timeout: 60000
       username: username
       password: password
       authenticationType: none
       timeToLive: 7000
       contextPath: "com.intesasanpaolo.connector.ws.gen.convenzionihostservice"
       soapVersion: 1.1
       soapAction: "http://tempuri.org/IConvenzioniHostService/GetCovenantPerConvenzione"
       enableMTOM: false
       mocked: false
       enabledTracing: true      
     GetRequisitiAdesioneConvenzioneConnector:
       endpoint: ${CONVENZIONI_SERVICE_WS_URL:http://servizibe-vdmc0.syssede.systest.sanpaoloimi.com:9018/ConvenzioniService.svc}
       timeout: 60000
       username: username
       password: password
       authenticationType: none
       timeToLive: 7000
       contextPath: "com.intesasanpaolo.connector.ws.gen.convenzioniservice"
       soapVersion: 1.1
       soapAction: "http://tempuri.org/IConvenzioniService/GetRequisitiAdesioneConvenzione"
       enableMTOM: false
       mocked: false
       enabledTracing: true

#### Security configuration: Everything allowed for test
keycloak:
  enabled: false
  auth-server-url: ${AUTH_SERVER_ENDPOINT}
  resource: bear-app
  realm: bear
  public-client: true
  ssl-required: external
  confidential-port: 0
  use-resource-role-mappings: true
  securityConstraints:
    -
      authRoles:
        - users

      securityCollections:
        -
          name: users reserved stuff
          patterns:
            - /preferences
