spring:
  profile: development
  application:
    name: "@project.artifactId@"
    version: "@project.version@ (@env.GIT_COMMIT@)"

error-manager:
  enabled: true
  
logging:
  level:
    root: INFO
    com.intesasanpaolo.bear: INFO
    com.intesasanpaolo.bear.config: INFO
    com.intesasanpaolo.bear.connector.bearcore: INFO
    org.keycloak: INFO

connectors:
  db2MultiDsConfigurations:
    items:
      MultiDataSourceDb2Connector:
        connectionTimeout: ${DATASOURCE_COND0DB2_CONNECTIONTIMEOUT:10000}
        connectionPoolSize: ${DATASOURCE_COND0DB2_CONNECTIONPOOLSIZE:5}
        mocked: false
        sources:
          - abi: ${ABI_SDDA:01025}
            uri: ${DATASOURCE_COND0DB2_URI:db2y.mframe.sanpaoloimi.com}
            port: ${DATASOURCE_COND0DB2_PORT:5250}
            dbName: ${DATASOURCE_COND0DB2_DBNAME:DB2YTOSG}
            readUsername: ${DATASOURCE_COND0DB2_DB2_USERNAME:u0h7129}
            readPassword: ${DATASOURCE_COND0DB2_DB2_PASSWORD:Alma0720}
            writeUsername: ${DATASOURCE_COND0DB2_DB2_USERNAME:u0h7129}
            writePassword: ${DATASOURCE_COND0DB2_DB2_PASSWORD:Alma0720}
          - abi: ${ABI_MDDA:03296}
            uri: ${DATASOURCE_COND0DB2_URI:db2y.mframe.sanpaoloimi.com}
            port: ${DATASOURCE_COND0DB2_PORT:5250}
            dbName: ${DATASOURCE_COND0DB2_DBNAME:DB2YTOSG}
            readUsername: ${DATASOURCE_COND0DB2_DB2_USERNAME:u0h7129}
            readPassword: ${DATASOURCE_COND0DB2_DB2_PASSWORD:Alma0720}
            writeUsername: ${DATASOURCE_COND0DB2_DB2_USERNAME:u0h7129}
            writePassword: ${DATASOURCE_COND0DB2_DB2_PASSWORD:Alma0720
          - abi: ${ABI_IDDA:03249}
            uri: ${DATASOURCE_COND0DB2_URI:db2y.mframe.sanpaoloimi.com}
            port: ${DATASOURCE_COND0DB2_PORT:5250}
            dbName: ${DATASOURCE_COND0DB2_DBNAME:DB2YTOSG}
            readUsername: ${DATASOURCE_COND0DB2_DB2_USERNAME:u0h7129}
            readPassword: ${DATASOURCE_COND0DB2_DB2_PASSWORD:Alma0720}
            writeUsername: ${DATASOURCE_COND0DB2_DB2_USERNAME:U0H7129}
            writePassword: ${DATASOURCE_COND0DB2_DB2_PASSWORD:Alma0720
          - abi: ${ABI_EDDA:10637}
            uri: ${DATASOURCE_COND0DB2_URI:db2y.mframe.sanpaoloimi.com}
            port: ${DATASOURCE_COND0DB2_PORT:5250}
            dbName: ${DATASOURCE_COND0DB2_DBNAME:DB2YTOSG}
            readUsername: ${DATASOURCE_COND0DB2_DB2_USERNAME:u0h7129}
            readPassword: ${DATASOURCE_COND0DB2_DB2_PASSWORD:Alma0720}
            writeUsername: ${DATASOURCE_COND0DB2_DB2_USERNAME:u0h7129}
            writePassword: ${DATASOURCE_COND0DB2_DB2_PASSWORD:Alma0720
          - abi: ${ABI_JDDA:03239}
            uri: ${DATASOURCE_COND0DB2_URI:db2y.mframe.sanpaoloimi.com}
            port: ${DATASOURCE_COND0DB2_PORT:5250}
            dbName: ${DATASOURCE_COND0DB2_DBNAME:DB2YTOSG}
            readUsername: ${DATASOURCE_COND0DB2_DB2_USERNAME:u0h7129}
            readPassword: ${DATASOURCE_COND0DB2_DB2_PASSWORD:Alma0720}
            writeUsername: ${DATASOURCE_COND0DB2_DB2_USERNAME:u0h7129}
            writePassword: ${DATASOURCE_COND0DB2_DB2_PASSWORD:Alma0720

#### Security configuration: Everything allowed for test
keycloak:
  enabled: false
  auth-server-url: ${AUTH_SERVER_ENDPOINT:dummy}
  resource: bear-app
  realm: bear
  public-client: true
  ssl-required: external
  confidential-port: 0
  use-resource-role-mappings: true
  securityConstraints:
    -
      authRoles:
        - users

      securityCollections:
        -
          name: users reserved stuff
          patterns:
            - /preferences
