configuration:
    env:
     - name: AUTH_SERVER_ENDPOINT
       value: https://gwad0-svil.syssede.systest.sanpaoloimi.com/auth/oauth
    ctg:
     - name: COND0
       acronimo: COND0
       servizio: COND0-CTGBS
       env: SVIL
       user: GACONNEC
    oracle:
     - name: CONDDATA
       acronimo: COND0
       servizio: COND0
       user: COND_APP   