configuration:         
  env: 
   -  name: ABI_SPIMI
      value: "01025"
   -  name: ABI_BKFID
      value: "03296"
   -  name: ABI_ISPBK
      value: "03239"
   -  name: ABI_BKIMI
      value: "03249"