configuration:
    env:
     - name: AUTH_SERVER_ENDPOINT
       value: https://gwad0-svil.syssede.systest.sanpaoloimi.com/auth/oauth
     - name: CONVENZIONI_HOST_SERVICE_WS_URL
       value: http://servizibe-vdmc0.syssede.systest.sanpaoloimi.com:9018/ConvenzioniHostService.svc
     - name: CONVENZIONI_SERVICE_WS_URL
       value: http://servizibe-vdmc0.syssede.systest.sanpaoloimi.com:9018/ConvenzioniService.svc
    ctg:
     - name: COND0
       acronimo: COND0
       servizio: COND0-CTGBS
       env: PROD
       user: GACONNEC