/*
 * GESTIONE
 * test
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.intesasanpaolo.bear.cond0.cjdispositiva.connector.rest.client.pcgestixme;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Setter;

import java.util.Objects;

import static com.intesasanpaolo.bear.cond0.cjdispositiva.utils.ApplicationConstants.COBOL_EMPTY;
/**
 * InputDatiInputAreaRapportoAccessorio
 */
@Setter
public class InputDatiInputAreaRapportoAccessorio {

    private String fiLRappAcc = COBOL_EMPTY;
    private String caTRappAcc = COBOL_EMPTY;
    private String numProgRappAcc = COBOL_EMPTY;

    @JsonProperty("FILRappAcc")
    public String getFiLRappAcc() {
        return fiLRappAcc;
    }

    @JsonProperty("CATRappAcc")
    public String getCaTRappAcc() {
        return caTRappAcc;
    }

    @JsonProperty("NumProgRappAcc")
    public String getNumProgRappAcc() {
        return numProgRappAcc;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InputDatiInputAreaRapportoAccessorio inputDatiInputAreaRapportoAccessorio = (InputDatiInputAreaRapportoAccessorio) o;
        return Objects.equals(fiLRappAcc, inputDatiInputAreaRapportoAccessorio.fiLRappAcc) &&
                Objects.equals(caTRappAcc, inputDatiInputAreaRapportoAccessorio.caTRappAcc) &&
                Objects.equals(numProgRappAcc, inputDatiInputAreaRapportoAccessorio.numProgRappAcc);
    }

    @Override
    public int hashCode() {
        return Objects.hash(fiLRappAcc, caTRappAcc, numProgRappAcc);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InputDatiInputAreaRapportoAccessorio {\n");

        sb.append("    fiLRappAcc: ").append(toIndentedString(fiLRappAcc)).append("\n");
        sb.append("    caTRappAcc: ").append(toIndentedString(caTRappAcc)).append("\n");
        sb.append("    numProgRappAcc: ").append(toIndentedString(numProgRappAcc)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
