/*
 * GESTIONE
 * test
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.intesasanpaolo.bear.cond0.cjdispositiva.connector.rest.client.pcgestixme;

import static com.intesasanpaolo.bear.cond0.cjdispositiva.utils.ApplicationConstants.COBOL_EMPTY;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Setter;

/**
 * Input
 */
@Setter
public class NewAccountInput {

	private Input input;

	@JsonProperty("input")
	public Input getInput() {
		return input;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spacesP
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	@Setter
	public static class Input {
		private NewAccountDatiInput datiInput = null;
		private String numSuperPratica = COBOL_EMPTY;
		private String numPratica = COBOL_EMPTY;

		@JsonProperty("DatiInput")
		public NewAccountDatiInput getDatiInput() {
			return datiInput;
		}

		@JsonProperty("NumSuperPratica")
		public String getNumSuperPratica() {
			return numSuperPratica;
		}

		@JsonProperty("NumPratica")
		public String getNumPratica() {
			return numPratica;
		}

		@Override
		public boolean equals(java.lang.Object o) {
			if (this == o) {
				return true;
			}
			if (o == null || getClass() != o.getClass()) {
				return false;
			}
			Input input = (Input) o;
			return Objects.equals(datiInput, input.datiInput) && Objects.equals(numSuperPratica, input.numSuperPratica)
					&& Objects.equals(numPratica, input.numPratica);
		}

		@Override
		public int hashCode() {
			return Objects.hash(datiInput, numSuperPratica, numPratica);
		}

		@Override
		public String toString() {
			StringBuilder sb = new StringBuilder();
			sb.append("class Input {\n");

			sb.append("    datiInput: ").append(toIndentedString(datiInput)).append("\n");
			sb.append("    numSuperPratica: ").append(toIndentedString(numSuperPratica)).append("\n");
			sb.append("    numPratica: ").append(toIndentedString(numPratica)).append("\n");
			sb.append("}");
			return sb.toString();
		}

		private String toIndentedString(java.lang.Object o) {
			if (o == null) {
				return "null";
			}
			return o.toString().replace("\n", "\n    ");
		}
	}
}
