/*
 * GESTIONE
 * test
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.intesasanpaolo.bear.cond0.cjdispositiva.connector.rest.client.pcgestixme;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Setter;

import java.util.Objects;

/**
 * OutputAreaDati
 */
@Setter
public class OutputAreaDati {

    private String codConvenzionePC;
    private String codConvenzioneFT;
    private String flagPerimetro;
    private String codProdotto;
    private String flagCambioOfferta;

    @JsonProperty("CodConvenzionePC")
    public String getCodConvenzionePC() {
        return codConvenzionePC;
    }

    @JsonProperty("CodConvenzioneFT")
    public String getCodConvenzioneFT() {
        return codConvenzioneFT;
    }

    @JsonProperty("FlagPerimetro")
    public String getFlagPerimetro() {
        return flagPerimetro;
    }

    @JsonProperty("CodProdotto")
    public String getCodProdotto() {
        return codProdotto;
    }

    @JsonProperty("FlagCambioOfferta")
    public String getFlagCambioOfferta() {
        return flagCambioOfferta;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OutputAreaDati outputAreaDati = (OutputAreaDati) o;
        return Objects.equals(codConvenzionePC, outputAreaDati.codConvenzionePC) &&
                Objects.equals(codConvenzioneFT, outputAreaDati.codConvenzioneFT) &&
                Objects.equals(flagPerimetro, outputAreaDati.flagPerimetro) &&
                Objects.equals(codProdotto, outputAreaDati.codProdotto) &&
                Objects.equals(flagCambioOfferta, outputAreaDati.flagCambioOfferta);
    }

    @Override
    public int hashCode() {
        return Objects.hash(codConvenzionePC, codConvenzioneFT, flagPerimetro, codProdotto, flagCambioOfferta);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OutputAreaDati {\n");

        sb.append("    codConvenzionePC: ").append(toIndentedString(codConvenzionePC)).append("\n");
        sb.append("    codConvenzioneFT: ").append(toIndentedString(codConvenzioneFT)).append("\n");
        sb.append("    flagPerimetro: ").append(toIndentedString(flagPerimetro)).append("\n");
        sb.append("    codProdotto: ").append(toIndentedString(codProdotto)).append("\n");
        sb.append("    flagCambioOfferta: ").append(toIndentedString(flagCambioOfferta)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
