/*
 * GESTIONE
 * test
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.intesasanpaolo.bear.cond0.cjdispositiva.connector.rest.client.pcgestixme;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Setter;

import java.util.Objects;

/**
 * OutputDatiDebugDatiErroreAreaErroreDB2
 */
@Setter
public class OutputDatiDebugDatiErroreAreaErroreDB2 {

    private String nomeTabella;
    private String filler1;
    private String sqLCode;
    private String filler2;

    @JsonProperty("NomeTabella")
    public String getNomeTabella() {
        return nomeTabella;
    }

    @JsonProperty("Filler1")
    public String getFiller1() {
        return filler1;
    }

    @JsonProperty("SQLCode")
    public String getSqLCode() {
        return sqLCode;
    }

    @JsonProperty("Filler2")
    public String getFiller2() {
        return filler2;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OutputDatiDebugDatiErroreAreaErroreDB2 outputDatiDebugDatiErroreAreaErroreDB2 = (OutputDatiDebugDatiErroreAreaErroreDB2) o;
        return Objects.equals(nomeTabella, outputDatiDebugDatiErroreAreaErroreDB2.nomeTabella) &&
                Objects.equals(filler1, outputDatiDebugDatiErroreAreaErroreDB2.filler1) &&
                Objects.equals(sqLCode, outputDatiDebugDatiErroreAreaErroreDB2.sqLCode) &&
                Objects.equals(filler2, outputDatiDebugDatiErroreAreaErroreDB2.filler2);
    }

    @Override
    public int hashCode() {
        return Objects.hash(nomeTabella, filler1, sqLCode, filler2);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OutputDatiDebugDatiErroreAreaErroreDB2 {\n");

        sb.append("    nomeTabella: ").append(toIndentedString(nomeTabella)).append("\n");
        sb.append("    filler1: ").append(toIndentedString(filler1)).append("\n");
        sb.append("    sqLCode: ").append(toIndentedString(sqLCode)).append("\n");
        sb.append("    filler2: ").append(toIndentedString(filler2)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
