configuration:
    oracle:
      - name: CONDDATA
        acronimo: COND0
        servizio: COND0
        user: COND_APP
    env:
     - name: AUTH_SERVER_ENDPOINT
       value: https://gwad0-prod.sede.corp.sanpaoloimi.com/auth/oauth
     - name: CALL_MOCK
       value: OFF